mapping = {
    'Philadelphia 76ers' : 'PHI',
    'Denver Nuggets': 'DEN',
    'Golden State Warriors' : 'GSW',
    'Milwaukee Bucks' : 'MIL',
    'Toronto Raptors' : 'TOR',
    'Los Angeles Clippers' : 'LAC',
    'San Antonio Spurs' : 'SAS',
    'Houston Rockets' : 'HOU',
    'Portland Trail Blazers' : 'POR',
    'Utah Jazz' : 'UTA',
    'Detroit Pistons' : 'DET',
    'Oklahoma City Thunder' : 'OKC',
    'Orlando Magic' : 'ORL',
    'Indiana Pacers' : 'IND',
    'Brooklyn Nets' : 'BRK',
    'Boston Celtics' : 'BOS',
    'Charlotte Hornets' : 'CHO',
    'Los Angeles Lakers' : 'LAL',
    'Sacramento Kings' : 'SAC',
    'Phoenix Suns' : 'PHO',
    'Dallas Mavericks' : 'DAL',
    'New Orleans Pelicans' : 'NOP',
    'Atlanta Hawks' : 'ATL',
    'Miami Heat' : 'MIA',
    'Washington Wizards' : 'WAS',
    'Minnesota Timberwolves' : 'MIN',
    'New York Knicks' : 'NYK',
    'Chicago Bulls' : 'CHI',
    'Memphis Grizzlies' : 'MEM',
    'Cleveland Cavaliers' : 'CLE',
}

mapping_abbrev_full = {v : k for k, v in mapping.items()}